# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: npm i -g @quasar/cli
      - run: npm i -g firebase-tools
      - run: yarn
      - run: quasar build -m ssr
      - run: quasar build
      - run: rm -rf public
      - run: cp -r dist/spa public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
      - run: firebase use default
      - run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      - run: echo build successful!
