# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feature CI/CD

on:
  push:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      mysecret: ${{ secrets.DEV_GPG_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: npm i -g @quasar/cli
      - run: npm i -g firebase-tools
      - run: yarn
      - run: ls -al
      - run: cd scripts
      - run: ls -al
      - run: chmod +x ./build.sh
      - run: chmod +x ./denv.sh
      - run: chmod +x ./env.sh
      - run: ls -al
      - run: cd ..
      - run: DEV_GPG_SECRET=${{ secrets.DEV_GPG_SECRET }} ./scripts/denv.sh #gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.DEV_GPG_SECRET }} --output ./devenv devenv.gpg
      - run: sudo sh -c ./scripts/build.sh $(cat devenv) #build the project
      - run: rm -rf public
      - run: cp -r dist/spa public
      - run: ls -al
      - run: pwd
      - run: cd public
      - run: ls -al
      - run: cd ..
      - name: Use dev
        uses: w9jds/firebase-action@master
        with:
          args: use dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - run: echo build successful!
