# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feature CI/CD

on:
  push:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: npm i -g @quasar/cli
      - run: npm i -g firebase-tools
      - run: yarn
      #- run: quasar build -m ssr
      - run: quasar build
      - run: rm -rf public
      - run: cp -r dist/spa public
      #- run: cp ./scripts/getenv.sh public/
      - run: cd public
      - run: echo ${{ secrets.DEV_ENV_VARS }} > env
      - run: cat env
      - run: ls -al
      - run: pwd
      - name: Deploy to Firebase 1
        uses: w9jds/firebase-action@master
        with:
          args: use dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase 2
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - run: echo build successful!
